name: Deploy insights-common-typescript

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/insights-common-typescript/**'

jobs:
  env:
    SCOPE_PACKAGE: '@redhat-cloud-services/insights-common-typescript'
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - uses: bahmutov/npm-install@v1
      - run: yarn ci --scope $SCOPE_PACKAGE
      - run: yarn build --scope $SCOPE_PACKAGE
      - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          DEPLOY_DIR: packages/insights-common-typescript
          SRC_PACKAGE_DIR: packages/insights-common-typescript
